### PR TITLE
Don't override summary when already exists - Analyzers [Classes/Methods/Records]

### PR DESCRIPTION
**Pull request by cestorer**

### CODE REVIEW

**Review by d1820 — COMMENTED** [review]
this breaks the existing update functionality.

**Comment by echoix** [comment]
Could it be a different suggestion to only add missing instead of overwriting all the manually tuned strings?
For example, I usually use the suggestion to add documentation everywhere and improve when needed. Later on, I add new stuff and want to add what's missing. Since I don't have a code fix suggestion that would add documentation on a single method or property (that isn't en empty summary or empty method argument suggestion), I need to preview the changes, copy from the preview the suggestions that I want to use, then paste them manually.

**Comment by d1820** [comment]
@echoix  so based on what you're saying are you constantly just rerunning the document whole file instead of just running individual methods you want to update or add documentation to? there should be two different selections available either document whole file, or document an individual method or property

**Comment by d1820** [comment]
@echoix others have seen this issue and it ended up being related to needing to upgrade visual studio it appears they released an interim version that has broken some extension functionalities upgrading to the latest version of VS fixed to those issues. are you on the latest version or can you confirm what version you are on please?

**Comment by echoix** [comment]
I found it! CPU usage was always high, and I was getting tired of hearing my fan. I looked up and one of the suggestions is to uncheck pull diagnostics and uncheck "Run code analysis in separate process". 

"Run code analysis in separate process" was checked like this: 
image

And if I uncheck "Run code analysis in separate process", suggestions for a single field or property works correctly!
image


I retried toggling on "Run code analysis in separate process", restarting Visual Studio, confirmed that the suggestions don't work, then unchecking again, restart VS, then the suggestions work.
And this was now with VS 2022 17.6, out yesterday.

**Comment by d1820** [comment]
wow.. hahah. I'll convert this flow to a bug and log it to take a look at

**Comment by echoix** [comment]
> wow.. hahah. I'll convert this flow to a bug and log it to take a look at

It's probably the way that extensions will be in the future, Out-Of-Process, just like the new WinForms designer. To decouple from having the IDE load an assembly, and can't unload it and once loaded, only that specific version is available for everything.

**Comment by d1820** [comment]
@echoix please refer to
https://github.com/d1820/CodeDocumentor/issues/22. moving forward

**Review by d1820 — COMMENTED** [review]
@cestorer  I have an idea of how to do this a little more flexable if interested reach out to discuss

**Comment by d1820** [comment]
Feature has been added to release 1.2.0.0 to support preserving summary text. Please review the release notes, or the readme for more details

**Pull request closed without merging**
